import type { Metadata } from "next";
import { Geist, Geist_Mono, Rubik, Vazirmatn } from "next/font/google";
import "./globals.css";

const font = Rubik({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={font.className}>{children}</body>
    </html>
  );
}
